### PR TITLE
Enhance document and example

### PR DESCRIPTION
**Pull request by HashLin-miso**
Just wanted to let you know about a couple of improvements in the MR:

1. I fixed the table display issue in the README.md file. You can check out the preview [here](https://github.com/MisoAI/target-miso/blob/5f5777c60a3585366a3e48f032826b93a4c218d0/README.md) after the fix.
2. Also, I made some changes to the PostgreSQL example. For products and users, I used `FULL_TABLE` in replication-method, and for interactions, I used `INCREMENTAL`.

Let me know if you have any questions!

### CODE REVIEW

**Comment by simonpai** [comment]
This is supposed to be a runnable example project. Can we add instruction of dummy data preparation for catalog and interactions?

**Comment by HashLin-miso** [comment]
Nice catch! I totally missed those dummy data in the folder. 😅

How about we make things easier and just change `INCREMENTAL` to `FULL_TABLE`? That way, we can fix the wrong configuration first, and then add some dummy data for the products and interactions. What do you say?

**Comment by simonpai** [comment]
> How about we make things easier and just change `INCREMENTAL` to `FULL_TABLE`? That way, we can fix the wrong configuration first, and then add some dummy data for the products and interactions. What do you say?

Agreed. Let's make it accurate first, and then make it better later!

**Comment by HashLin-miso** [comment]
> > How about we make things easier and just change `INCREMENTAL` to `FULL_TABLE`? That way, we can fix the wrong configuration first, and then add some dummy data for the products and interactions. What do you say?
> 
> Agreed. Let's make it accurate first, and then make it better later!

Done. Please help me review it again. Thanks.

**Pull request merged**
